/* GENERATED by scripts/ingest-media.ts — do not edit by hand.
 * Ids of case-media entries whose converted WebP asset exists under
 * public/media/<project>/<id>.webp. Re-run the ingest script after adding
 * files to upload/. Client-safe (plain strings only). */
export const AVAILABLE_CASE_MEDIA: string[] = [];
